name: "Open CB: compare builds"
run-name: ${{ inputs.build-name != '' && inputs.build-name || format('version={0}, buildId={1} vs version=${2}, buildId={3}', inputs.scala-version, inputs.build-id, inputs.compare-with-scala-version, inputs.compare-with-build-id) }}

on:
  workflow_dispatch:
    inputs:
      build-name:
        type: string
        description: "Custom name of the job in GitHub Actions"
        default: ""
      scala-version:
        type: string
        description: "Reference version of Scala"
        default: ""
      compare-with-scala-version:
        type: string
        description: "Version of Scala to compare against"
        default: ""
      build-id:
        type: string
        description: "Optional version of reference build id"
        default: ""
      compare-with-build-id:
        type: string
        description: "Optional version of build id to compare against. BuildId is equal to the GitHub Action Id, based on the Action URL format: `github.com/<org>/<repo>/actions/runs/<build-id>`)"
        default: ""
jobs:
  create-raport:
    runs-on: ubuntu-22.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.4
      - name: Install coursier
        uses: coursier/setup-action@v1
        with:
          apps: scala-cli

      - name: Generate raport
        env:
          ES_USER: ${{ secrets.OPENCB_ELASTIC_USER }}
          ES_PASSWORD: ${{ secrets.OPENCB_ELASTIC_PSWD }}
        run: |
          scalaVersion=${{ inputs.scala-version }}
          lastRC="$(./scripts/lastVersionRC.sc)"
          lastStable=$(./scripts/lastVersionStable.sc)

          scala-cli scripts/raport-regressions.scala scripts/md_printer.scala -- $scalaVersion > raport-full.md
          scala-cli scripts/raport-regressions.scala scripts/md_printer.scala -- $scalaVersion --compareWith=$lastRC > raport-compare-$lastRC.md
          scala-cli scripts/raport-regressions.scala scripts/md_printer.scala -- $scalaVersion --compareWith=$lastStable > raport-compare-$lastStable.md

          lastWeeklyVersionFile=./last-successfull-weekly-version
          lastWeeklyVersion=$(cat $lastWeeklyVersionFile) && \
            scala-cli scripts/raport-regressions.scala scripts/md_printer.scala -- $scalaVersion --compareWith=$lastWeeklyVersion > raport-compare-$lastWeeklyVersion.md || true
          echo "$scalaVersion" > $lastWeeklyVersionFile

      - name: Upload raports
        uses: actions/upload-artifact@v3
        with:
          name: build-raports
          path: ${{ github.workspace }}/raport-*.md

      - name: Push raport
        uses: ./.github/actions/push-raport-to-gh-pages
        with:
          artifact-name: build-raports
          file-to-pick: raport-full.md
          build-title: ${{ inputs.scala-version }}
          token: ${{ secrets.OPENCB_CONFIG_UPDATE_TOKEN }}
